package com.example.noteitapp.ui.fragments

import android.os.Bundle
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.Button
import android.widget.EditText
import android.widget.Toast
import androidx.core.content.ContextCompat
import androidx.lifecycle.ViewModelProvider
import com.example.noteitapp.R
import com.example.noteitapp.data.Note
import com.example.noteitapp.ui.viewmodels.NoteViewModel

class AddNoteFragment : Fragment() {

    private lateinit var noteViewModel: NoteViewModel
    private lateinit var editTitle: EditText
    private lateinit var editSubtitle: EditText
    private lateinit var editContent: EditText
    private lateinit var saveButton: Button
    private var selectedColor: Int = R.color.red // Default color

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        val view = inflater.inflate(R.layout.fragment_add_note, container, false)

        // Initialize ViewModel
        noteViewModel = ViewModelProvider(this).get(NoteViewModel::class.java)

        // Bind views
        editTitle = view.findViewById(R.id.editTitle)
        editSubtitle = view.findViewById(R.id.editSubtitle)
        editContent = view.findViewById(R.id.editContent)
        saveButton = view.findViewById(R.id.saveButton)

        // Handle color selection
        view.findViewById<View>(R.id.colorYellow1).setOnClickListener{
            selectedColor=R.color.colorAccent
        }
        view.findViewById<View>(R.id.colorYellow).setOnClickListener {
            selectedColor = R.color.yellow
        }
        view.findViewById<View>(R.id.colorBlue1).setOnClickListener {
            selectedColor = R.color.blue
        }
        view.findViewById<View>(R.id.colorBlue).setOnClickListener {
            selectedColor = R.color.noteColor6
        }
        view.findViewById<View>(R.id.colorGreen).setOnClickListener {
            selectedColor = R.color.noteColor3
        }
        view.findViewById<View>(R.id.colorGreen1).setOnClickListener {
            selectedColor = R.color.noteColor5
        }


        // Handle save button click
        saveButton.setOnClickListener {
            val title = editTitle.text.toString()
            val subtitle = editSubtitle.text.toString()
            val content = editContent.text.toString()
            if (title.isNotEmpty() && content.isNotEmpty()) {
                val note = Note(
                    id = 0, // Auto-generated by Room
                    title = title,
                    subtitle = subtitle,
                    content = content,
                    color = selectedColor
                )
                noteViewModel.insert(note)
                parentFragmentManager.popBackStack() // Go back to the previous screen
            } else {
                Toast.makeText(requireContext(), "Please fill in all fields", Toast.LENGTH_SHORT).show()
            }
        }

        return view
    }
}